name: snmalloc CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # GitHub doesn't natively support *BSD, but we can run them in VMs on Mac /
  # Linux runners
  bsd:
    strategy:
      matrix:
        # Build each combination of OS, version, and release/debug variants
        # FreeBSD and OpenBSD run on xhyve, netbsd needs qemu
        os:
          - name: freebsd
            version: '12.4'
            host: macos-12
            dependencies: pkg ins -y cmake ninja
            enabled: true
          # Tests are failing on OpenBSD, so disable for now.
          #- name: openbsd
          #  version: '7.2'
          #  host: macos-12
          #  dependencies: pkg_add -I cmake ninja
          # NetBSD fails to produce any output in 25 minutes, so disable for now.
          #- name: netbsd
          #  version: '9.2'
          #  host: ubuntu-latest
          #  dependencies: pkgin -y install cmake ninja
        build-type: [ Debug ]
      # Don't abort runners if a single one fails
      fail-fast: false
    # Kill these jobs if they take too long.
    timeout-minutes: 25
    runs-on: ${{ matrix.os.host }}
    name: ${{ matrix.os.name }}-${{ matrix.os.version}} ${{ matrix.build-type }}
    steps:
    - uses: actions/checkout@v3
    - uses: mxschmitt/action-tmate@v3
    - uses: cross-platform-actions/action@v0.10.0
      with:
        operating_system: ${{ matrix.os.name }}
        architecture: x86-64
        version: ${{ matrix.os.version}}
        shell: bash
        run: |
          sudo ${{ matrix.os.dependencies }}
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build-type}} -G Ninja
          cd ${{github.workspace}}/build
          NINJA_STATUS="%p [%f:%s/%t] %o/s, %es" ninja
          ctest -j 4 --output-on-failure -E '(perf-.*)|(.*-malloc$)' --timeout 400
